/*

CREATE DATABASE CONTROLEPONTO; 

*/

USE CONTROLEPONTO;

CREATE TABLE UF (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    UF CHAR(2) NOT NULL UNIQUE,
    NOME_UF VARCHAR(40) NOT NULL
)

CREATE TABLE CARGO (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CARGO VARCHAR(60) NOT NULL,
    SALARIO_BASE DECIMAL(10, 2)
)

CREATE TABLE LOGIN (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(40) NOT NULL UNIQUE,
    PWD VARCHAR(40) NOT NULL
)

CREATE TABLE APONTAMENTO_HORAS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    DATACAD DATE NOT NULL,
    HRENTRADA TIME,
    HRSAIDAALMOCO TIME,
    HRVOLTAALMOCO TIME,
    HRSAIDA TIME
)

CREATE TABLE FUNCIONARIOS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    ENDERECO VARCHAR(80) NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    CIDADE VARCHAR(40) NOT NULL,
    TELEFONE VARCHAR(11),
    CELULAR VARCHAR(12),
    IDUF INT,
    IDLOGIN INT,
    IDCARGO INT,
    IDAPONTAMENTO INT
)




